### ISSUE TITLE
Unable to set snippets path after update 

### ISSUE THREAD

**Issue by UserOEM** [deadlyjack/acode-plugin-snippets#19]
Hi. After an update a few days ago, I don't see 'set snippets path' anymore. Can you please investigate.

**Comment by deadlyjack** [comment]
I forgot to mention it is moved to it's setting on plugin page. go to plugin and you'll see settings icon click on it you will the set snippets path.

**Comment by UserOEM** [comment]
Thanks!

**Comment by sekedus** [comment]
> I forgot to mention it is moved to it's setting on plugin page. go to plugin and you'll see settings icon click on it you will the set snippets path.

Please update the [`readme.md`](https://github.com/deadlyjack/acode-plugin-snippets/blob/main/readme.md#how-to-enable-custom-snippets) file.
