### ISSUE TITLE
Custom snippet Doesn't work

### ISSUE THREAD

**Issue by Gul7333** [deadlyjack/acode-plugin-snippets#25]
Not showing in command pallet...
I also used setting options in snippet and set snippet directory...
Then I added some custom snippet..but they are not working...all snippet are working except those which I created...
I refreshed and double checked everything but custom added snippet are not working...
Also in command pallet no set directory or resset directory options are showing

Problem
1: not showing in command pallet
2: custom added snippet are not working

Predefined snippet are working like BD equal to border in css

Android 10
Model: Tecno Pova LD7

**Comment by jhlight13** [comment]
I'm having the same problem. I tried setting the snippet directly to a folder I had a snippets file, but my snippets never worked.  I even tried coping my snippets file to the snippets folder of the plugin folder, but that didn't seem to work either.

Predefined snippets are hit or miss. Sometimes all the predefined snippets work, sometimes none of the snippets will display.

Android 13

**Comment by ezeaniiandrew** [comment]
Just putting this comment out in the wild. If you're facing a similar challenge. The following steps should help you resolve the issue:

1) Upgrade your Acode app to the latest version

2) The title of your snippet file should be a programming language. For example, if your are writing snippets for React, the file containing your snippets should be named "javascript.snippets" and not "react.snippets" or any other name that is not a programming language.

Note: You should be aware that your custom snippets will replace the plugins default snippets.

**Comment by jhlight13** [comment]
> Just putting this comment out in the wild. If you're facing a similar challenge. The following steps should help you resolve the issue:
> 
> 1. Upgrade your Acode app to the latest version
> 2. The title of your snippet file should be a programming language. For example, if your are writing snippets for React, the file containing your snippets should be named "javascript.snippets" and not "react.snippets" or any other name that is not a programming language.
> 
> Note: You should be aware that your custom snippets will replace the plugins default snippets.

Thank you so much for the explanation. I was trying to use a randomly named snippet file not knowing that the name needed to match the programming language.

**Comment by islam2hamy** [comment]
Hello ,

any help how to make snippet with regex
to find a paragraph and replace it (HTML)

thank you

**Comment by ezeaniiandrew** [comment]
> Hello ,
> 
> any help how to make snippet with regex to find a paragraph and replace it (HTML)
> 
> thank you

You don't need a snippet for this. Simply use the native search (Ctrl + f) and replace method. Just make sure that regular expression is active in the search settings.

**Comment by islam2hamy** [comment]
> > Hello ,
> > any help how to make snippet with regex to find a paragraph and replace it (HTML)
> > thank you
> 
> You don't need a snippet for this. Simply use the native search (Ctrl + f) and replace method. Just make sure that regular expression is active in the search settings.

Thank you for reply ,

i have a lot of repeated find and replace with multiple files .

so, i think snippet is the good choice

isn't it ?
